
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           98865
     no. of nonzeroes in lower triangle of a =         6797268
     no. of nonzeroes in the factor l        =        47338101
     ratio of nonzeroes in factor (min/max)  =          0.9961
     number of super nodes                   =            2258
     maximum order of a front matrix         =            1518
     maximum size of a front matrix          =         1152921
     maximum size of a front trapezoid       =          718602
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      2.9621D+10
     no. of floating point ops for solve     =      1.8144D+08
     ratio of flops for factor (min/max)     =          0.9932
     ratio of allocated memory (max/min)     =          1.0083
     number of positive pivots               =           98865
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.031250        0.036629
     time (cpu & wall) for ordering          =        0.359375        0.368338
     time (cpu & wall) for other matrix prep =        0.046875        0.049753
     time (cpu & wall) for value input       =        0.109375        0.147468
     time (cpu & wall) for matrix distrib.   =        0.312500        0.316234
     time (cpu & wall) for numeric factor    =        1.703125        1.919922
     computational rate (gflops) for factor  =       17.392275       15.428345
     time (cpu & wall) for numeric solve     =        0.062500        0.061906
     computational rate (gflops) for solve   =        2.903103        2.930954
     effective I/O rate (GB/sec) for solve   =       10.815761       10.919523

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        367205.        3. MB
                95-   1        393216.        3. MB        366687.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        733892.        6. MB


  Solver Memory allocated on core    0       =      335.829 MB
  Solver Memory allocated on core    1       =      333.061 MB
  Total Solver Memory allocated by all cores =      668.889 MB

