
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           17934
     no. of nonzeroes in lower triangle of a =          282461
     no. of nonzeroes in the factor l        =         1749253
     ratio of nonzeroes in factor (min/max)  =          0.9757
     number of super nodes                   =             891
     maximum order of a front matrix         =             276
     maximum size of a front matrix          =           38226
     maximum size of a front trapezoid       =           23348
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.7531D+08
     no. of floating point ops for solve     =      6.1222D+06
     ratio of flops for factor (min/max)     =          0.9699
     ratio of allocated memory (max/min)     =          1.0227
     number of positive pivots               =           17934
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.002179
     time (cpu & wall) for ordering          =        0.046875        0.054592
     time (cpu & wall) for other matrix prep =        0.015625        0.012731
     time (cpu & wall) for value input       =        0.000000        0.005078
     time (cpu & wall) for matrix distrib.   =        0.031250        0.019503
     time (cpu & wall) for numeric factor    =        0.031250        0.054080
     computational rate (gflops) for factor  =        5.609963        3.241698
     time (cpu & wall) for numeric solve     =        0.015625        0.003963
     computational rate (gflops) for solve   =        0.391819        1.544872
     effective I/O rate (GB/sec) for solve   =        1.459755        5.755552

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         97933.        1. MB
                95-   1         98304.        1. MB         95822.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        193755.        1. MB


  Solver Memory allocated on core    0       =       15.187 MB
  Solver Memory allocated on core    1       =       14.850 MB
  Total Solver Memory allocated by all cores =       30.037 MB

