
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            9867
     no. of nonzeroes in lower triangle of a =          459825
     no. of nonzeroes in the factor l        =         2530611
     ratio of nonzeroes in factor (min/max)  =          0.8802
     number of super nodes                   =             309
     maximum order of a front matrix         =             726
     maximum size of a front matrix          =          263901
     maximum size of a front trapezoid       =          212220
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      8.3683D+08
     no. of floating point ops for solve     =      9.4560D+06
     ratio of flops for factor (min/max)     =          0.8552
     ratio of allocated memory (max/min)     =          1.1731
     number of positive pivots               =            9867
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.003660
     time (cpu & wall) for ordering          =        0.046875        0.043700
     time (cpu & wall) for other matrix prep =        0.000000        0.005652
     time (cpu & wall) for value input       =        0.015625        0.006836
     time (cpu & wall) for matrix distrib.   =        0.031250        0.035225
     time (cpu & wall) for numeric factor    =        0.093750        0.092024
     computational rate (gflops) for factor  =        8.926203        9.093593
     time (cpu & wall) for numeric solve     =        0.015625        0.005800
     computational rate (gflops) for solve   =        0.605183        1.630202
     effective I/O rate (GB/sec) for solve   =        2.254662        6.073459

     no input or output performed

  Solver Memory allocated on core    0       =       20.766 MB
  Solver Memory allocated on core    1       =       24.361 MB
  Total Solver Memory allocated by all cores =       45.127 MB

