



  Performance statistics for DSP solver: icalls =    492

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            8502
     no. of nonzeroes in lower triangle of a =          293463
     no. of nonzeroes in the factor l        =         1083197
     ratio of nonzeroes in factor (min/max)  =          0.9432
     number of super nodes                   =             321
     maximum order of a front matrix         =             303
     maximum size of a front matrix          =           46056
     maximum size of a front trapezoid       =           45495
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.3702D+08
     no. of floating point ops for solve     =      3.9147D+06
     ratio of flops for factor (min/max)     =          0.8788
     ratio of allocated memory (max/min)     =          1.0085
     number of positive pivots               =            8478
     number of negative pivots               =              24
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      1.0000D-04
     number of 1x1 pivots                    =               3
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =               0
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.002497
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.007993
     time (cpu & wall) for matrix distrib.   =        0.015625        0.019943
     time (cpu & wall) for numeric factor    =        0.015625        0.030058
     computational rate (gflops) for factor  =        8.768988        4.558369

     no input or output performed

  Solver Memory allocated on core    0       =       23.466 MB
  Solver Memory allocated on core    1       =       23.267 MB
  Total Solver Memory allocated by all cores =       46.733 MB

