
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            9446
     no. of nonzeroes in lower triangle of a =           87421
     no. of nonzeroes in the factor l        =          680319
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =             697
     maximum order of a front matrix         =             176
     maximum size of a front matrix          =           15576
     maximum size of a front trapezoid       =           10731
     METIS reordering method used 
     no. of floating point ops for factor    =      4.6068D+07
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =            9446
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               2
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.003062
     time (cpu & wall) for ordering          =        0.046875        0.036007
     time (cpu & wall) for other matrix prep =        0.000000        0.006901
     time (cpu & wall) for value input       =        0.000000        0.003569
     time (cpu & wall) for matrix distrib.   =        0.015625        0.008445
     time (cpu & wall) for numeric factor    =        0.046875        0.033276
     computational rate (gflops) for factor  =        0.982775        1.384388

     no input or output performed

  Total Solver Memory allocated              =       11.582 MB
